"""initial schema

Revision ID: 5882befa3dbe
Revises: 
Create Date: 2026-01-26 01:08:19.876104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5882befa3dbe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benchmark_nav',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('benchmark_name', sa.String(length=100), nullable=False),
    sa.Column('nav_date', sa.Date(), nullable=False),
    sa.Column('nav_value', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('benchmark_name', 'nav_date', name='uq_benchmark_date')
    )
    op.create_index('ix_benchmark_date', 'benchmark_nav', ['benchmark_name', 'nav_date'], unique=False)
    op.create_table('fund_managers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mutual_funds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheme_code', sa.String(length=50), nullable=False),
    sa.Column('fund_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('sub_category', sa.String(length=100), nullable=True),
    sa.Column('benchmark', sa.String(length=100), nullable=True),
    sa.Column('aum', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('ter', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('launch_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheme_code')
    )
    op.create_table('fund_manager_mapping',
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fund_id'], ['mutual_funds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manager_id'], ['fund_managers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fund_id', 'manager_id')
    )
    op.create_table('fund_metrics_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('std_deviation', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('beta', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('sharpe_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('sortino_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('alpha', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('r_squared', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('upside_capture', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('downside_capture', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('rolling_return_1y', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('rolling_return_3y', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['fund_id'], ['mutual_funds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nav_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('nav_date', sa.Date(), nullable=False),
    sa.Column('nav_value', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['fund_id'], ['mutual_funds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fund_id', 'nav_date', name='uq_fund_nav_date')
    )
    op.create_index('ix_nav_fund_date', 'nav_data', ['fund_id', 'nav_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_nav_fund_date', table_name='nav_data')
    op.drop_table('nav_data')
    op.drop_table('fund_metrics_snapshot')
    op.drop_table('fund_manager_mapping')
    op.drop_table('mutual_funds')
    op.drop_table('fund_managers')
    op.drop_index('ix_benchmark_date', table_name='benchmark_nav')
    op.drop_table('benchmark_nav')
    # ### end Alembic commands ###
